#-------------------------------------------
#  Custom Button Card Templates
#  https://github.com/custom-cards/button-card
#-------------------------------------------
button_card_templates: !include_dir_merge_named btn_card_templates/

#-------------------------------------------
#  Kiosk Mode
#  https://github.com/maykar/kiosk-mode
#-------------------------------------------
kiosk_mode:
  hide_header: false
  hide_sidebar: false
  hide_overflow: false

  mobile_settings:
    hide_header: false
    hide_sidebar: false
    hide_overflow: false
    custom_width: 800

#-------------------------------------------
#  Default View
#-------------------------------------------
views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(5, 1fr) 0
      grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .        .          .        ."
        "sidebar  plex        media    bedroom    temps    ."
        "sidebar  camera      outside  home       laundry  ."
        "sidebar  footer      footer   footer     footer   ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(6, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .            ."
            ".  sidebar     sidebar      ."
            ".  home        bedroom      ."
            ".  media       outside      ."
            ".  camera      plex         ."
            ".  temps       laundry      ."
            ".  footer      footer       ."
            ".  .           .            ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(4, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .           ."
            "sidebar  home        bedroom     ."
            "sidebar  media       outside     ."
            "sidebar  camera      plex        ."
            "sidebar  temps       laundry     ."
            "sidebar  footer      footer      ."
            "sidebar  .           .           ."
    cards:
      #extra_styles fix
      - type: custom:button-card
        styles:
          card:
            - display: none

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar_template

          - type: grid
            cards:
              - type: button
                icon: mdi:information-outline
                tap_action:
                  !include popup/sidebar_information.yaml
                hold_action:
                  action: none

              - type: button
                icon: mdi:alert-rhombus
                tap_action:
                  !include popup/sidebar_active_alerts.yaml
                hold_action:
                  action: none
                card_mod:
                  style: |
                    :host {
                      --card-mod-icon:
                      {% if is_state('sensor.template_oakland_alert_1', 'on') %}
                        {% set alert_event1 = state_attr('sensor.template_oakland_alert_1', 'alert_event') %}
                        {% set alert_event2 = state_attr('sensor.template_oakland_alert_2', 'alert_event') %}

                        {% if ((alert_event1 is search('warning', ignorecase=True)) or (alert_event2 is search('warning', ignorecase=True))) %}
                          mdi:weather-lightning;
                        {% elif ((alert_event1 is search('special', ignorecase=True)) or (alert_event2 is search('special', ignorecase=True))) %}
                          mdi:weather-cloudy-alert;
                        {% elif ((alert_event1 is search('watch', ignorecase=True)) or (alert_event2 is search('watch', ignorecase=True))) %}
                          mdi:weather-cloudy-alert;
                        {% elif ((alert_event1 is search('winter', ignorecase=True)) or (alert_event2 is search('winter', ignorecase=True))) %}
                          mdi:snowflake-alert;
                        {% else %}
                          mdi:check-bold;
                        {% endif %}
                      {% else %}
                        {% if not is_state('sensor.template_unavailable_entities', 'unknown') %}
                          {% if (states('sensor.template_unavailable_entities') | int(default=0) > 0) and not is_state('timer.startup_missing_delay', 'active') %}
                            mdi:alert-rhombus;
                          {% else %}
                            mdi:check-bold;
                          {% endif %}
                        {% else %}
                          mdi:check-bold;
                        {% endif %}
                      {% endif %}
                    }

              - type: button
                icon: mdi:arrow-up-bold-circle-outline
                tap_action:
                  !include popup/sidebar_update.yaml
                hold_action:
                  action: none

      #################################################
      #                                               #
      #                    PLEX                       #
      #                                               #
      #################################################

      - type: grid
        title: Plex
        view_layout:
          grid-area: plex
        columns: 1
        cards:

          - type: custom:swipe-card
            start_card: 1
            parameters:
              roundLengths: true
              effect: coverflow
              speed: 650
              spaceBetween: 20
              freeModeMomentum: true
              threshold: 7
              autoplay:
                delay: 20000
              coverflowEffect:
                rotate: 80
                depth: 300
                slideShadows: true
            cards:

              - type: custom:button-card
                entity: sensor.plex_recently_added
                tap_action:
                  action: none
                template:
                  - conditional_media
                  - recently_downloaded
                  - icon_plex
                variables:
                  download_index: >
                    [[[
                      return parseInt('1');
                    ]]]

              - type: custom:button-card
                entity: sensor.plex_recently_added
                tap_action:
                  action: none
                template:
                  - conditional_media
                  - recently_downloaded
                  - icon_plex
                variables:
                  download_index: >
                    [[[
                      return parseInt('2');
                    ]]]

              - type: custom:button-card
                entity: sensor.plex_recently_added
                tap_action:
                  action: none
                template:
                  - conditional_media
                  - recently_downloaded
                  - icon_plex
                variables:
                  download_index: >
                    [[[
                      return parseInt('3');
                    ]]]

      #################################################
      #                                               #
      #                    MEDIA                      #
      #                                               #
      #################################################

      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 2
        cards:

          - type: custom:button-card
            entity: media_player.yamaha_receiver_family_room
            name: Yamaha
            template:
              - base
              - icon_monitors
              - circle
              - loader
            hold_action:
              !include popup/media_yamaha.yaml
            variables:
              circle_input: >
                [[[
                  return entity === undefined ?
                    null :
                    parseInt(entity.attributes.volume_level * 100);
                ]]]

          - type: custom:button-card
            entity: media_player.samsung_1080p
            name: TV
            tap_action:
              !include popup/family_room_tv.yaml
            template:
              - base
              - icon_tv

      #################################################
      #                                               #
      #                   BEDROOM                     #
      #                                               #
      #################################################

      - type: grid
        title: Bedroom
        view_layout:
          grid-area: bedroom
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.oli_night_light
            name: Oli Night
            template:
              - base
              - icon_hue
              - loader

          # https://github.com/tuya/tuya-home-assistant/pull/387
          #- type: custom:button-card
          #  entity: fan.master_bedroom
          #  name: Master
          #  hold_action:
          #    !include popup/master_fan.yaml
          #  template:
          #    - base
          #    - icon_fan2
          #    - circle
          #    - loader
          #  variables:
          #    circle_input: >
          #      [[[
          #        return entity === undefined ?
          #          null :
          #          parseInt(entity.attributes.percentage);
          #      ]]]

      #################################################
      #                                               #
      #                   CAMERAS                     #
      #                                               #
      #################################################

      - type: grid
        title: Cameras
        view_layout:
          grid-area: camera
        columns: 1
        cards:

          - type: custom:swipe-card
            start_card: 1
            parameters:
              roundLengths: true
              effect: coverflow
              speed: 650
              threshold: 7
              coverflowEffect:
                rotate: 80
                depth: 300
            cards:
              - type: grid
                columns: 1
                cards:
                  - type: 'custom:webrtc-camera'
                    entity: camera.masterbedroom
                    poster: https://home-assistant.io/images/cast/splash.png
                    muted: true
                    background: true

              - type: grid
                columns: 1
                cards:
                  - type: 'custom:webrtc-camera'
                    entity: camera.olibedroom
                    poster: https://home-assistant.io/images/cast/splash.png
                    muted: true
                    background: true

              - type: grid
                columns: 1
                cards:
                  - type: 'custom:webrtc-camera'
                    entity: camera.garage
                    poster: https://home-assistant.io/images/cast/splash.png
                    muted: true
                    background: true

              - type: grid
                columns: 1
                cards:
                  - type: 'custom:webrtc-camera'
                    entity: camera.floating
                    poster: https://home-assistant.io/images/cast/splash.png
                    muted: true
                    background: true


      #################################################
      #                                               #
      #                  Outside                      #
      #                                               #
      #################################################

      - type: grid
        title: Outside
        view_layout:
          grid-area: outside
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.outside_front_door_light
            name: Front
            template:
              - base
              - icon_hue
              - loader

          - type: custom:button-card
            entity: lock.front_door
            name: Door
            template:
              - base
              - lock
              - icon_door
              - loader

          - type: custom:button-card
            entity: light.outside_garage_lights
            name: Garage
            template:
              - base
              - icon_hue
              - loader

          - type: custom:button-card
            entity: binary_sensor.garage_contact
            name: Garage
            tap_action:
              !include popup/home_garage.yaml
            template:
              - base
              - icon_shutter

      #################################################
      #                                               #
      #                    HOME                       #
      #                                               #
      #################################################

      - type: grid
        title: Home
        view_layout:
          grid-area: home
        columns: 2
        cards:

          - type: custom:button-card
            entity: person.weston
            name: Weston
            triggers_update:
              - sensor.weston_last_changed
            tap_action:
              !include popup/home_weston.yaml
            hold_action:
              action: none
            variables:
              retain: sensor.weston_last_changed
            template: person

          - type: custom:button-card
            entity: person.ana
            name: Ana
            triggers_update:
              - sensor.ana_last_changed
            tap_action:
              !include popup/home_ana.yaml
            hold_action:
              action: none
            variables:
              retain: sensor.ana_last_changed
            template: person

          - type: custom:button-card
            entity: climate.thermostat
            name: Climate
            tap_action:
              !include popup/climate_status.yaml
            template:
              - base
              - icon_ac
              - climate
            variables:
              circle_input: >
                [[[
                  return entity === undefined ?
                    null :
                    entity.attributes.temperature;
                ]]]

          - type: custom:button-card
            entity: input_boolean.fresh_air_mode_en
            name: Air Mode
            template:
              - base
              - icon_toggle

      #################################################
      #                                               #
      #                    TEMPS                      #
      #                                               #
      #################################################

      - type: grid
        title: Environment
        view_layout:
          grid-area: temps
        columns: 2
        cards:
          - type: custom:button-card
            entity: sensor.garage_temp_temperature
            name: Garage
            custom_fields:
              graph:
                card:
                  entities:
                    - sensor.garage_temp_temperature
            template:
             - temp

          - type: custom:button-card
            entity: sensor.thermostat_current_temperature
            name: Office
            custom_fields:
              graph:
                card:
                  entities:
                    - sensor.thermostat_current_temperature
            template:
             - temp

          - type: custom:button-card
            entity: sensor.basement_temperature
            name: Basement
            custom_fields:
              graph:
                card:
                  entities:
                    - sensor.basement_temperature
            template:
             - temp

          - type: custom:button-card
            entity: sensor.dark_sky_apparent_temperature
            name: Outside
            custom_fields:
              graph:
                card:
                  entities:
                    - sensor.dark_sky_apparent_temperature
            template:
             - temp

      #################################################
      #                                               #
      #                  LAUNDRY                      #
      #                                               #
      #################################################

      - type: grid
        title: 'Laundry'
        view_layout:
          grid-area: laundry
        columns: 2
        cards:

          - type: custom:button-card
            entity: sensor.washer
            name: Washer
            tap_action:
              !include popup/laundry_status.yaml
            hold_action:
              action: none
            template:
              - laundry
              - icon_washer
            variables:
              circle_input: >
                [[[
                  return entity === undefined ?
                    null :
                    entity.attributes.remain_time;
                ]]]

          - type: custom:button-card
            entity: sensor.dryer
            name: Dryer
            tap_action:
              !include popup/laundry_status.yaml
            hold_action:
              action: none
            template:
              - laundry
              - icon_dryer
            variables:
              circle_input: >
                [[[
                  return entity === undefined ?
                    null :
                    entity.attributes.remain_time;
                ]]]

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: custom:button-card
        view_layout:
          grid-area: footer
        template: footer