#-------------------------------------------
#  APC Battery Backup
#  https://www.home-assistant.io/components/apcupsd/
#-------------------------------------------
- platform: apcupsd
  resources:
    - status
    - linev
    - loadpct
    - bcharge
    - timeleft
    - mbattchg
    - battv