#-------------------------------------------
#  Dark Sky Weather
#-------------------------------------------
- platform: darksky
  api_key: !secret dark_sky_api
  forecast:
    - 0
  hourly_forecast:
    - 0
    - 1
  monitored_conditions:
    - summary
    - icon
    - apparent_temperature
    - temperature
    - temperature_high
    - temperature_low
    - precip_intensity
    - precip_probability
    - cloud_cover
  scan_interval:
    days: 0
    hours: 1
    minutes: 0
    seconds: 0
    milliseconds: 0