#-------------------------------------------
#  Heating History Stats
#  https://www.home-assistant.io/components/history_stats/
#-------------------------------------------

- platform: history_stats
  name: Heating Hours Today
  entity_id: sensor.template_operating_state
  state: 'heating'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Heating Hours Yesterday
  entity_id: sensor.template_operating_state
  state: 'heating'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: history_stats
  name: Heating Hours Two Days Ago
  entity_id: sensor.template_operating_state
  state: 'heating'
  type: time
  end: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - 86400 }}'
  duration:
    hours: 24

#-------------------------------------------
#  Cooling History Stats
#  https://www.home-assistant.io/components/history_stats/
#-------------------------------------------
- platform: history_stats
  name: Cooling Hours Today
  entity_id: sensor.template_operating_state
  state: 'cooling'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Cooling Hours Yesterday
  entity_id: sensor.template_operating_state
  state: 'cooling'
  type: time
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24

- platform: history_stats
  name: Cooling Hours Two Days Ago
  entity_id: sensor.template_operating_state
  state: 'cooling'
  type: time
  end: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - 86400 }}'
  duration:
    hours: 24