#-------------------------------------------
#  Plex Recently Added
#  https://github.com/custom-components/sensor.plex_recently_added
#  https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
#-------------------------------------------
- platform: plex_recently_added
  token: !secret plex_token
  host: !secret plex_host
  port: !secret plex_port
  max: 5
  img_dir: /
  image_resolution: 500
  exclude_keywords:
    - Linus
    - RenoVision
    - Meld
    - Lawrence
    - ShortCircuit
    - Techquickie
    - Knorr
    - Andrei
    - Steven
    - Chris
  section_types:
    - show
    - movie