#-------------------------------------------
#  Release Notes
#-------------------------------------------

- platform: rest
  name: hass_release_notes
  resource: https://api.github.com/repos/home-assistant/core/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
    - html_url
    - tag_name
  scan_interval: 21600
  headers: &rest_header
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: HAS Releases

- platform: rest
  name: hass_release_notes_rc
  authentication: basic
  username: !secret github_username 
  password: !secret github_token
  resource: https://api.github.com/repos/home-assistant/core/releases?per_page=1
  value_template: >
    {{ value_json[0].name }}
  json_attributes:
    - body
    - html_url
    - tag_name
  scan_interval: 21600
  headers: *rest_header

- platform: rest
  name: adguardhome_release_notes
  authentication: basic
  username: !secret github_username 
  password: !secret github_token
  resource: https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
    - html_url
    - tag_name
  scan_interval: 21600
  headers: *rest_header

- platform: rest
  name: photoprism_release_notes
  authentication: basic
  username: !secret github_username 
  password: !secret github_token
  resource: https://api.github.com/repos/photoprism/photoprism/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
    - html_url
    - tag_name
  scan_interval: 21600
  headers: *rest_header

- platform: rest
  name: fireflyIII_release_notes
  authentication: basic
  username: !secret github_username 
  password: !secret github_token
  resource: https://api.github.com/repos/firefly-iii/firefly-iii/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
    - html_url
    - tag_name
  scan_interval: 21600
  headers: *rest_header

- platform: rest
  name: papermerge_release_notes
  authentication: basic
  username: !secret github_username 
  password: !secret github_token
  resource: https://api.github.com/repos/papermerge/papermerge-core/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
    - html_url
    - tag_name
  scan_interval: 21600
  headers: *rest_header

- platform: rest
  name: homeassistant_desktop_release_notes
  authentication: basic
  username: !secret github_username 
  password: !secret github_token
  resource: https://api.github.com/repos/mrvnklm/homeassistant-desktop/releases/latest
  value_template: >
    {{ value_json.name }}
  json_attributes:
    - body
    - html_url
    - tag_name
  scan_interval: 21600
  headers: *rest_header

#-------------------------------------------
#  Plex Server
#-------------------------------------------

- platform: rest
  name: plex_server_release_notes
  json_attributes_path: "$.response.data"
  json_attributes:
    - update_available
    - platform
    - release_date
    - requirements
    - extra_info
    - changelog_added
    - changelog_fixed
    - label
    - distro
    - distro_build
  resource: !secret tautulli_api_get_pms_update
  value_template: "{{ value_json.response.data.version }}"
  scan_interval: 21600

- platform: rest
  name: plex_version_installed
  json_attributes_path: "$.response.data"
  json_attributes:
    - pms_name
    - pms_platform
    - pms_plexpass
  resource: !secret tautulli_api_get_server_info
  value_template: "{{ value_json.response.data.pms_version }}"
  scan_interval: 21600