#-------------------------------------------
#  MQTT Sensors
#  https://www.home-assistant.io/integrations/sensor.mqtt/
#-------------------------------------------

- platform: command_line
  name: udm_unifios
  command: !secret udm_unifios
  value_template: |-
    {% set json = value_json.data[2] %}
    {% set json2 = value_json.data[1] %}
    {{ json.model }}|
    {{ json["system-stats"].cpu }}|
    {{ json.temperatures[1].value | round(1) }}|
    {{ json["system-stats"].mem }}|
    {{ ((json.storage[1].used / json.storage[1].size) * 100) | round(1) }}|
    {{ json2.internet }}|
    {{ json.startup_timestamp | timestamp_local }}|
    {{ json.displayable_version }}|
    {{ json.upgradable }}
  scan_interval: 120