####################################################
#                                                  #
#                    CUSTOMIZE                     #
#                                                  #
####################################################
homeassistant:
  customize:

    #-------------------------------------------
    #  template
    #-------------------------------------------
    light.oli_night_light:
      friendly_name: Oli Night Light

    #-------------------------------------------
    #  home_garage.yaml
    #-------------------------------------------
    binary_sensor.garage_contact:
      friendly_name: Garage Door

    #-------------------------------------------
    #  sidebar_information.yaml
    #-------------------------------------------
    sensor.docker_1cpu:
      friendly_name: Processor
      icon: mdi:chip

    sensor.docker_memory_percent:
      friendly_name: Memory
      icon: mdi:memory

    sensor.docker_version:
      friendly_name: Docker Version
      icon: custom:docker-watchtower

    sensor.hass_version_installed:
      friendly_name: Version Installed

    sensor.hass_version_latest:
      friendly_name: Version Latest

    sensor.home_assistant_log:
      icon: mdi:file-document
      friendly_name: Log

    sensor.home_assistant_v2_db:
      friendly_name: Database
      icon: mdi:database

    #-------------------------------------------
    #  climate_status.yaml
    #-------------------------------------------
    sensor.dark_sky_apparent_temperature_0h:
      friendly_name: Outside Temp

    sensor.dark_sky_daytime_high_temperature_0d:
      friendly_name: High Temp

    #-------------------------------------------
    #  Batteries
    #-------------------------------------------
    sensor.front_door_battery:
      friendly_name: Front Door

    sensor.garage_battery:
      friendly_name: Garage Battery

    sensor.office_window_battery:
      friendly_name: Office Window

    sensor.dining_room_window_battery:
      friendly_name: Dining Room Window

    sensor.master_bedroom_window_battery:
      friendly_name: Master Bedroom Window

    #-------------------------------------------
    #  Rest Software Sensors
    #-------------------------------------------
    sensor.homeassistant_desktop_release_notes:
      friendly_name: HA Desktop App

    sensor.adguardhome_release_notes:
      friendly_name: AdguardHome

    sensor.photoprism_release_notes:
      friendly_name: Photoprism

    sensor.fireflyiii_release_notes:
      friendly_name: FireflyIII

    sensor.papermerge_release_notes:
      friendly_name: Papermerge

    #-------------------------------------------
    #  Laundry
    #-------------------------------------------
    sensor.template_washer_door_lock:
      icon: mdi:lock
      friendly_name: Washer Door Lock

    sensor.template_washer_time_display:
      icon: mdi:camera-timer
      friendly_name: Washer Time Display

    sensor.template_dryer_time_display:
      icon: mdi:camera-timer
      friendly_name: Dryer Time Display

    sensor.template_blank:
      friendly_name: Blank Sensor