sensor:
  #---------------------------------------------------------------------------------------
  #  APC Battery Backup
  #  https://www.home-assistant.io/components/apcupsd/
  #---------------------------------------------------------------------------------------
  - platform: apcupsd
    resources:
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - mbattchg
      - battv

  #---------------------------------------------------------------------------------------
  # Plex Recently Added
  # https://github.com/NemesisRE/sensor.plex_recently_added
  # https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
  #---------------------------------------------------------------------------------------
  - platform: plex_recently_added
    name: plex_recently_added_show
    token: !secret plex_token
    host: !secret plex_host
    port: !secret plex_port
    max: 5
    img_dir: /
    image_resolution: 900
    exclude_keywords:
      - RenoVision
      - Meld
      - Lawrence
      - ShortCircuit
      - Techquickie
      - Knorr
      - Andrei
      - Steven
      - Chris
    section_types:
      - show

  #---------------------------------------------------------------------------------------
  #  Weather Alerts
  #  https://github.com/custom-components/weatheralerts
  #---------------------------------------------------------------------------------------
  - platform: weatheralerts
    state: MI
    zone: 69
    county: 125
    scan_interval: 60

  #---------------------------------------------------------------------------------------
  # History Stats
  # https://www.home-assistant.io/components/history_stats/
  #---------------------------------------------------------------------------------------

  - platform: history_stats
    name: Heating Hours Today
    entity_id: sensor.template_operating_state
    state: 'heating'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Heating Hours Yesterday
    entity_id: sensor.template_operating_state
    state: 'heating'
    type: time
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  - platform: history_stats
    name: Heating Hours Two Days Ago
    entity_id: sensor.template_operating_state
    state: 'heating'
    type: time
    end: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - 86400 }}'
    duration:
      hours: 24

  - platform: history_stats
    name: Cooling Hours Today
    entity_id: sensor.template_operating_state
    state: 'cooling'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Cooling Hours Yesterday
    entity_id: sensor.template_operating_state
    state: 'cooling'
    type: time
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      hours: 24

  - platform: history_stats
    name: Cooling Hours Two Days Ago
    entity_id: sensor.template_operating_state
    state: 'cooling'
    type: time
    end: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - 86400 }}'
    duration:
      hours: 24

  #---------------------------------------------------------------------------------------
  # Command Line
  # https://www.home-assistant.io/integrations/sensor.command_line/
  #---------------------------------------------------------------------------------------

  - platform: command_line
    name: udm_unifios
    command: !secret udm_unifios
    value_template: |-
      {% set udmprose = value_json.data[4] %}
      {% set ualr6v2 = value_json.data[2] %}
      {{ udmprose.model }}|
      {{ udmprose["system-stats"].cpu }}|
      {{ udmprose.temperatures[1].value | round(1) }}|
      {{ udmprose["system-stats"].mem }}|
      {{ ((udmprose.storage[1].used / udmprose.storage[1].size) * 100) | round(1) }}|
      {{ ualr6v2.internet }}|
      {{ udmprose.startup_timestamp | timestamp_local }}|
      {{ udmprose.displayable_version }}|
      {{ udmprose.upgradable }}|
      {{ ualr6v2.upgradable }}|
      {{ ualr6v2.version }}|
      {{ ualr6v2.upgrade_to_firmware | default(false) }}
    scan_interval: 120

  - platform: command_line
    name: hacs_installed
    command: |-
      python3 << EOF
      import os, json
      installed = {"repositories": []}
      path = "/config/.storage/hacs/"
      for file in os.listdir(path):
          name, ext = os.path.splitext(file)
          if ext == ".hacs":
              hacs_file = path + file
              with open(hacs_file, "r") as file:
                  dict = json.load(file)
                  name = dict["data"]["full_name"]
                  installed["repositories"] += [name]
                  file.close()
      print(json.dumps(installed))
      EOF
    value_template: >
      {{ value_json.repositories | count }}
    json_attributes:
      - repositories
    scan_interval: 86400

  #---------------------------------------------------------------------------------------
  # Uptime
  # https://www.home-assistant.io/integrations/uptime/
  #---------------------------------------------------------------------------------------
  - platform: uptime

  #---------------------------------------------------------------------------------------
  # Time & Date
  # https://www.home-assistant.io/integrations/time_date/
  #---------------------------------------------------------------------------------------
  - platform: time_date
    display_options:
      - time
      - date